name: Deploy Application

on:
  push:
    branches: [ \"main\" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
        - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Auth GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - id: 'gke-auth'
      name: GKE auth
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: gke-${{ inputs.environment || 'dev' }}
        location: europe-west1

    - name: Helm Deploy App
      run: |
        helm upgrade --install ecommerce ./helm/charts/ecommerce \
          --values helm/values/${{ inputs.environment }}.yaml \
          --namespace ecommerce \
          --create-namespace

    - name: Deploy Monitoring
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
          --values helm/values/${{ inputs.environment }}.yaml \
          --namespace monitoring \
          --create-namespace

